-- MySQL Script generated by MySQL Workbench
-- Sat Oct 23 22:46:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema cmd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cmd` ;

-- -----------------------------------------------------
-- Schema cmd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cmd` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
-- -----------------------------------------------------
-- Schema dbminishop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbminishop` ;

-- -----------------------------------------------------
-- Schema dbminishop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbminishop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------





USE `cmd` ;

-- -----------------------------------------------------
-- Table `cmd`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`departments` ;

CREATE TABLE IF NOT EXISTS `cmd`.`departments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `farther_department_id` INT(11) NULL,
  `manager_id` INT(11) NULL,
  `create_by` VARCHAR(45) NULL,
  `modify_by` VARCHAR(45) NULL,
  `create_date` VARCHAR(45) NULL,
  `modify_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cmd`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`positions` ;

CREATE TABLE IF NOT EXISTS `cmd`.`positions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `department_id` INT(11) NOT NULL,
  `is_manager` TINYINT NULL,
  `create_by` VARCHAR(45) NULL,
  `modify_by` VARCHAR(45) NULL,
  `create_date` VARCHAR(45) NULL,
  `modify_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chucvu_phongban1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_chucvu_phongban1`
    FOREIGN KEY (`department_id`)
    REFERENCES `cmd`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cmd`.`statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`statuses` ;

CREATE TABLE IF NOT EXISTS `cmd`.`statuses` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmd`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`employees` ;

CREATE TABLE IF NOT EXISTS `cmd`.`employees` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `date _of_birth` VARCHAR(20) NULL DEFAULT 0,
  `email` VARCHAR(45) NULL,
  `phone_number` VARCHAR(15) NULL,
  `manager_id` INT(10) NULL,
  `create_by` VARCHAR(45) NULL,
  `modify_by` VARCHAR(45) NULL,
  `create_date` VARCHAR(45) NULL,
  `modify_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cmd`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`tasks` ;

CREATE TABLE IF NOT EXISTS `cmd`.`tasks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status_id` INT(10) NOT NULL,
  `creator_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_statuses1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_tasks_employees1_idx` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_statuses1`
    FOREIGN KEY (`status_id`)
    REFERENCES `cmd`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_employees1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `cmd`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cmd`.`proposal_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`proposal_types` ;

CREATE TABLE IF NOT EXISTS `cmd`.`proposal_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cmd`.`proposals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`proposals` ;

CREATE TABLE IF NOT EXISTS `cmd`.`proposals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `proposal_type_id` INT(11) NOT NULL,
  `creator_id` INT(11) NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dexuat_TrangThai1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_proposals_proposal_types1_idx` (`proposal_type_id` ASC) VISIBLE,
  INDEX `fk_proposals_employees1_idx` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `fk_dexuat_TrangThai1`
    FOREIGN KEY (`status_id`)
    REFERENCES `cmd`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposals_proposal_types1`
    FOREIGN KEY (`proposal_type_id`)
    REFERENCES `cmd`.`proposal_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposals_employees1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `cmd`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cmd`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`roles` ;

CREATE TABLE IF NOT EXISTS `cmd`.`roles` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `position_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_roles_positions1_idx` (`position_id` ASC) VISIBLE,
  CONSTRAINT `fk_roles_positions1`
    FOREIGN KEY (`position_id`)
    REFERENCES `cmd`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmd`.`data_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`data_types` ;

CREATE TABLE IF NOT EXISTS `cmd`.`data_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmd`.`proposal_type_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`proposal_type_details` ;

CREATE TABLE IF NOT EXISTS `cmd`.`proposal_type_details` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `proposal_types_id` INT(11) NOT NULL,
  `field_id` INT NULL,
  `field_name` VARCHAR(45) NULL,
  `data_type_id` INT NOT NULL,
  `create_by` VARCHAR(45) NULL,
  `modify_by` VARCHAR(45) NULL,
  `create_date` VARCHAR(45) NULL,
  `modify_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_type_details_data_types1_idx` (`data_type_id` ASC) VISIBLE,
  INDEX `fk_proposal_type_details_proposal_types1_idx` (`proposal_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_type_details_data_types1`
    FOREIGN KEY (`data_type_id`)
    REFERENCES `cmd`.`data_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposal_type_details_proposal_types1`
    FOREIGN KEY (`proposal_types_id`)
    REFERENCES `cmd`.`proposal_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmd`.`departments_employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`departments_employees` ;

CREATE TABLE IF NOT EXISTS `cmd`.`departments_employees` (
  `departments_id` INT(11) NOT NULL,
  `employees_id` INT(11) NOT NULL,
  INDEX `fk_departments_employees_departments1_idx` (`departments_id` ASC) VISIBLE,
  INDEX `fk_departments_employees_employees1_idx` (`employees_id` ASC) VISIBLE,
  CONSTRAINT `fk_departments_employees_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `cmd`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_employees_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `cmd`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cmd`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`options` ;

CREATE TABLE IF NOT EXISTS `cmd`.`options` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmd`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`permissions` ;

CREATE TABLE IF NOT EXISTS `cmd`.`permissions` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmd`.`role_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`role_details` ;

CREATE TABLE IF NOT EXISTS `cmd`.`role_details` (
  `id` INT(10) NOT NULL,
  `option_id` INT(10) NOT NULL,
  `role_id` INT(10) NOT NULL,
  `permission_id` INT(10) NOT NULL,
  `create_by` VARCHAR(45) NULL,
  `modify_by` VARCHAR(45) NULL,
  `create_date` VARCHAR(45) NULL,
  `modify_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_details_options1_idx` (`option_id` ASC) VISIBLE,
  INDEX `fk_role_details_roles1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_role_details_permissions1_idx` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_details_options1`
    FOREIGN KEY (`option_id`)
    REFERENCES `cmd`.`options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_details_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `cmd`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_details_permissions1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `cmd`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmd`.`task_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`task_details` ;

CREATE TABLE IF NOT EXISTS `cmd`.`task_details` (
  `id` INT NOT NULL,
  `receiver_id` INT(11) NOT NULL,
  `task_id` INT(11) NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `create_by` VARCHAR(45) NULL,
  `modify_by` VARCHAR(45) NULL,
  `create_date` VARCHAR(45) NULL,
  `modify_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_GiaoViec_nhanvien1_idx` (`receiver_id` ASC) VISIBLE,
  INDEX `fk_task_details_tasks1_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_GiaoViec_nhanvien1`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `cmd`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_details_tasks1`
    FOREIGN KEY (`task_id`)
    REFERENCES `cmd`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cmd`.`approval_steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`approval_steps` ;

CREATE TABLE IF NOT EXISTS `cmd`.`approval_steps` (
  `id` INT NOT NULL,
  `approval_step_name` VARCHAR(45) NULL,
  `approval_step_index ` INT NULL,
  `proposal_types_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_approval_steps_proposal_types1_idx` (`proposal_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_approval_steps_proposal_types1`
    FOREIGN KEY (`proposal_types_id`)
    REFERENCES `cmd`.`proposal_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cmd`.`proposal_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`proposal_permissions` ;

CREATE TABLE IF NOT EXISTS `cmd`.`proposal_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proposal_types_id` INT(11) NOT NULL,
  `departments_id` INT(11) NOT NULL,
  `positions_id` INT(11) NOT NULL,
  `employees_id` INT(11) NOT NULL,
  INDEX `fk_proposal_permissions_proposal_types1_idx` (`proposal_types_id` ASC) VISIBLE,
  INDEX `fk_proposal_permissions_departments1_idx` (`departments_id` ASC) VISIBLE,
  INDEX `fk_proposal_permissions_positions1_idx` (`positions_id` ASC) VISIBLE,
  INDEX `fk_proposal_permissions_employees1_idx` (`employees_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_proposal_permissions_proposal_types1`
    FOREIGN KEY (`proposal_types_id`)
    REFERENCES `cmd`.`proposal_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposal_permissions_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `cmd`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposal_permissions_positions1`
    FOREIGN KEY (`positions_id`)
    REFERENCES `cmd`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposal_permissions_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `cmd`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmd`.`positions_has_employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`positions_has_employees` ;

CREATE TABLE IF NOT EXISTS `cmd`.`positions_has_employees` (
  `positions_id` INT(11) NOT NULL,
  `employees_id` INT(11) NOT NULL,
  PRIMARY KEY (`positions_id`, `employees_id`),
  INDEX `fk_positions_has_employees_employees1_idx` (`employees_id` ASC) VISIBLE,
  INDEX `fk_positions_has_employees_positions1_idx` (`positions_id` ASC) VISIBLE,
  CONSTRAINT `fk_positions_has_employees_positions1`
    FOREIGN KEY (`positions_id`)
    REFERENCES `cmd`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_positions_has_employees_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `cmd`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cmd`.`proposal_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`proposal_details` ;

CREATE TABLE IF NOT EXISTS `cmd`.`proposal_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proposals_id` INT(11) NOT NULL,
  `field_id` VARCHAR(45) NULL,
  `content` VARCHAR(200) NULL,
  `create_by` VARCHAR(45) NULL,
  `modify_by` VARCHAR(45) NULL,
  `create_date` VARCHAR(45) NULL,
  `modify_date` VARCHAR(45) NULL,
  INDEX `fk_proposal_details_proposals1_idx` (`proposals_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_proposal_details_proposals1`
    FOREIGN KEY (`proposals_id`)
    REFERENCES `cmd`.`proposals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmd`.`approval_step_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmd`.`approval_step_details` ;

CREATE TABLE IF NOT EXISTS `cmd`.`approval_step_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `approval_steps_id` INT NOT NULL,
  `employees_id` INT(11) NOT NULL,
  `departments_id` INT(11) NOT NULL,
  `positions_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_approval_step_details_approval_steps1_idx` (`approval_steps_id` ASC) VISIBLE,
  INDEX `fk_approval_step_details_employees1_idx` (`employees_id` ASC) VISIBLE,
  INDEX `fk_approval_step_details_departments1_idx` (`departments_id` ASC) VISIBLE,
  INDEX `fk_approval_step_details_positions1_idx` (`positions_id` ASC) VISIBLE,
  CONSTRAINT `fk_approval_step_details_approval_steps1`
    FOREIGN KEY (`approval_steps_id`)
    REFERENCES `cmd`.`approval_steps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_approval_step_details_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `cmd`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_approval_step_details_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `cmd`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_approval_step_details_positions1`
    FOREIGN KEY (`positions_id`)
    REFERENCES `cmd`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `dbminishop` ;

-- -----------------------------------------------------
-- Table `dbminishop`.`MAUSANPHAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`MAUSANPHAM` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`MAUSANPHAM` (
  `mamau` INT NOT NULL AUTO_INCREMENT,
  `tenmau` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`mamau`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbminishop`.`DANHMUCSANPHAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`DANHMUCSANPHAM` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`DANHMUCSANPHAM` (
  `madanhmuc` INT NOT NULL AUTO_INCREMENT,
  `tendanhmuc` VARCHAR(100) NULL DEFAULT NULL,
  `hinhdanhmuc` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`madanhmuc`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbminishop`.`SANPHAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`SANPHAM` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`SANPHAM` (
  `masanpham` INT NOT NULL AUTO_INCREMENT,
  `madanhmuc` INT NULL DEFAULT NULL,
  `tensanpham` VARCHAR(100) NULL DEFAULT NULL,
  `giatien` VARCHAR(50) NULL DEFAULT NULL,
  `mota` TEXT NULL DEFAULT NULL,
  `hinhsanpham` TEXT NULL DEFAULT NULL,
  `gianhcho` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`masanpham`),
  INDEX `FK_SANPHAM_DANHMUC` (`madanhmuc` ASC) VISIBLE,
  CONSTRAINT `FK_SANPHAM_DANHMUC`
    FOREIGN KEY (`madanhmuc`)
    REFERENCES `dbminishop`.`DANHMUCSANPHAM` (`madanhmuc`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbminishop`.`SIZESANPHAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`SIZESANPHAM` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`SIZESANPHAM` (
  `masize` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`masize`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbminishop`.`CHITIETSANPHAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`CHITIETSANPHAM` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`CHITIETSANPHAM` (
  `machitietsanpham` INT NOT NULL AUTO_INCREMENT,
  `masanpham` INT NULL DEFAULT NULL,
  `masize` INT NULL DEFAULT NULL,
  `mamau` INT NULL DEFAULT NULL,
  `soluong` INT NULL DEFAULT NULL,
  `ngaynhap` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`machitietsanpham`),
  INDEX `FK_CHITIET_SANPHAM` (`masanpham` ASC) VISIBLE,
  INDEX `FK_CHITIET_SIZE` (`masize` ASC) VISIBLE,
  INDEX `FK_CHITIET_MAUSANPHAM` (`mamau` ASC) VISIBLE,
  CONSTRAINT `FK_CHITIET_MAUSANPHAM`
    FOREIGN KEY (`mamau`)
    REFERENCES `dbminishop`.`MAUSANPHAM` (`mamau`),
  CONSTRAINT `FK_CHITIET_SANPHAM`
    FOREIGN KEY (`masanpham`)
    REFERENCES `dbminishop`.`SANPHAM` (`masanpham`),
  CONSTRAINT `FK_CHITIET_SIZE`
    FOREIGN KEY (`masize`)
    REFERENCES `dbminishop`.`SIZESANPHAM` (`masize`))
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbminishop`.`HOADON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`HOADON` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`HOADON` (
  `mahoadon` INT NOT NULL AUTO_INCREMENT,
  `tenkhachhang` VARCHAR(100) NULL DEFAULT NULL,
  `sodt` CHAR(12) NULL DEFAULT NULL,
  `diachigiaohang` VARCHAR(200) NULL DEFAULT NULL,
  `tinhtrang` TINYINT NULL DEFAULT NULL,
  `ngaylap` VARCHAR(50) NULL DEFAULT NULL,
  `hinhthucgiaohang` VARCHAR(50) NULL DEFAULT NULL,
  `ghichu` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`mahoadon`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbminishop`.`CHITIETHOADON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`CHITIETHOADON` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`CHITIETHOADON` (
  `mahoadon` INT NOT NULL,
  `machitietsanpham` INT NOT NULL,
  `soluong` INT NULL DEFAULT NULL,
  `giatien` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`mahoadon`, `machitietsanpham`),
  INDEX `FK_CTHOADON_CTSANPHAM` (`machitietsanpham` ASC) VISIBLE,
  CONSTRAINT `FK_CTHOADON_CTSANPHAM`
    FOREIGN KEY (`machitietsanpham`)
    REFERENCES `dbminishop`.`CHITIETSANPHAM` (`machitietsanpham`),
  CONSTRAINT `FK_CTHOADON_HOADON`
    FOREIGN KEY (`mahoadon`)
    REFERENCES `dbminishop`.`HOADON` (`mahoadon`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbminishop`.`CHITIETKHUYENMAI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`CHITIETKHUYENMAI` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`CHITIETKHUYENMAI` (
  `makhuyenmai` INT NOT NULL,
  `masanpham` INT NOT NULL,
  PRIMARY KEY (`makhuyenmai`, `masanpham`),
  INDEX `FK_CHITIETKHUYENMAI_SANPHAM` (`masanpham` ASC) VISIBLE,
  CONSTRAINT `FK_CHITIETKHUYENMAI_SANPHAM`
    FOREIGN KEY (`masanpham`)
    REFERENCES `dbminishop`.`SANPHAM` (`masanpham`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbminishop`.`CHUCVU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`CHUCVU` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`CHUCVU` (
  `machucvu` INT NOT NULL AUTO_INCREMENT,
  `tenchucvu` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`machucvu`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbminishop`.`KHUYENMAI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`KHUYENMAI` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`KHUYENMAI` (
  `makhuyenmai` INT NOT NULL AUTO_INCREMENT,
  `tenkhuyenmai` VARCHAR(200) NULL DEFAULT NULL,
  `thoigianbatdau` VARCHAR(50) NULL DEFAULT NULL,
  `thoigianketthuc` VARCHAR(50) NULL DEFAULT NULL,
  `mota` TEXT NULL DEFAULT NULL,
  `hinhkhuyenmai` TEXT NULL DEFAULT NULL,
  `giagiam` INT NULL DEFAULT NULL,
  PRIMARY KEY (`makhuyenmai`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbminishop`.`NHANVIEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`NHANVIEN` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`NHANVIEN` (
  `manhanvien` INT NOT NULL AUTO_INCREMENT,
  `hoten` VARCHAR(30) NULL DEFAULT NULL,
  `diachi` VARCHAR(200) NULL DEFAULT NULL,
  `gioitinh` TINYINT NULL DEFAULT NULL,
  `cmnd` CHAR(14) NULL DEFAULT NULL,
  `machucvu` INT NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `tendangnhap` VARCHAR(50) NULL DEFAULT NULL,
  `matkhau` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`manhanvien`),
  INDEX `FK_NHANVIEN_CHUCVU` (`machucvu` ASC) VISIBLE,
  CONSTRAINT `FK_NHANVIEN_CHUCVU`
    FOREIGN KEY (`machucvu`)
    REFERENCES `dbminishop`.`CHUCVU` (`machucvu`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbminishop`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbminishop`.`USER` ;

CREATE TABLE IF NOT EXISTS `dbminishop`.`USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
